[2024-12-13T17:02:39.768+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-13T17:02:39.775+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movielens_pipeline.train_and_predict manual__2024-12-13T17:02:21.744359+00:00 [queued]>
[2024-12-13T17:02:39.778+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movielens_pipeline.train_and_predict manual__2024-12-13T17:02:21.744359+00:00 [queued]>
[2024-12-13T17:02:39.778+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-13T17:02:39.784+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): train_and_predict> on 2024-12-13 17:02:21.744359+00:00
[2024-12-13T17:02:39.787+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-13T17:02:39.788+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2024-12-13T17:02:39.789+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'movielens_pipeline', 'train_and_predict', 'manual__2024-12-13T17:02:21.744359+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/movielens_pipeline.py', '--cfg-path', '/tmp/tmpp3l3v5qq']
[2024-12-13T17:02:39.790+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask train_and_predict
[2024-12-13T17:02:39.810+0000] {task_command.py:467} INFO - Running <TaskInstance: movielens_pipeline.train_and_predict manual__2024-12-13T17:02:21.744359+00:00 [running]> on host 86634416f965
[2024-12-13T17:02:39.843+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movielens_pipeline' AIRFLOW_CTX_TASK_ID='train_and_predict' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T17:02:21.744359+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T17:02:21.744359+00:00'
[2024-12-13T17:02:39.844+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-13T17:02:39.844+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-13T17:02:39.844+0000] {logging_mixin.py:190} INFO - Current task name:train_and_predict state:running start_date:2024-12-13 17:02:39.775824+00:00
[2024-12-13T17:02:39.844+0000] {logging_mixin.py:190} INFO - Dag name:movielens_pipeline and current dag run status:running
[2024-12-13T17:02:39.845+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-13T17:02:39.845+0000] {train_and_predict.py:20} INFO - Initializing Spark session.
[2024-12-13T17:02:39.965+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/train_and_predict.py", line 24, in train_and_predict
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-13T17:02:39.973+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-13T17:02:39.973+0000] {logging_mixin.py:190} INFO - Task start:2024-12-13 17:02:39.775824+00:00 end:2024-12-13 17:02:39.973107+00:00 duration:0.197283
[2024-12-13T17:02:39.974+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): train_and_predict> dag:<DAG: movielens_pipeline> dagrun:<DagRun movielens_pipeline @ 2024-12-13 17:02:21.744359+00:00: manual__2024-12-13T17:02:21.744359+00:00, state:running, queued_at: 2024-12-13 17:02:21.761114+00:00. externally triggered: True>
[2024-12-13T17:02:39.974+0000] {logging_mixin.py:190} INFO - Failure caused by [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-13T17:02:39.974+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=movielens_pipeline, task_id=train_and_predict, run_id=manual__2024-12-13T17:02:21.744359+00:00, execution_date=20241213T170221, start_date=20241213T170239, end_date=20241213T170239
[2024-12-13T17:02:39.982+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-13T17:02:39.983+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task train_and_predict ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 85)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/train_and_predict.py", line 24, in train_and_predict
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-12-13T17:02:40.012+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-13T17:02:40.021+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-13T17:02:40.021+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
